#!/usr/bin/env python3
"""Run a reproducible external-process base/head match matrix."""

from __future__ import annotations

import argparse
import datetime as dt
import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path

import match_summary
from common import ScriptError, quote_command, run_command


@dataclass(frozen=True)
class GitMetadata:
    ref: str
    sha: str


@dataclass(frozen=True)
class MatrixConfig:
    base_build: Path
    head_build: Path
    base_repo: Path
    head_repo: Path
    openings: Path
    depths: list[int]
    games: int
    seed: int
    out_dir: Path
    runner: Path
    base_binary: Path
    head_binary: Path
    summary_script: Path
    external_timeout_ms: int
    allow_errors: bool


@dataclass(frozen=True)
class DepthRun:
    depth: int
    run_dir: Path
    engines_path: Path
    match_path: Path
    summary_path: Path
    command_path: Path
    runner_command: list[str]
    summary_command: list[str]


@dataclass(frozen=True)
class DepthResult:
    run: DepthRun
    summary: match_summary.Summary | None
    runner_exit_code: int
    error: str | None = None


def parse_depth_list(value: str) -> list[int]:
    depths: list[int] = []
    for raw_part in value.split(","):
        part = raw_part.strip()
        if not part:
            raise ScriptError(f"invalid depth list: {value}")
        try:
            depth = int(part)
        except ValueError as exc:
            raise ScriptError(f"invalid depth value: {part}") from exc
        if depth <= 0:
            raise ScriptError(f"depth must be positive: {depth}")
        depths.append(depth)
    if not depths:
        raise ScriptError("depth list must not be empty")
    return depths


def _ensure_no_pipe(value: Path, label: str) -> None:
    if "|" in str(value):
        raise ScriptError(f"{label} must not contain '|': {value}")


def render_engine_config(config: MatrixConfig, depth: int) -> str:
    for label, value in (
        ("base repo", config.base_repo),
        ("head repo", config.head_repo),
        ("base binary", config.base_binary),
        ("head binary", config.head_binary),
    ):
        _ensure_no_pipe(value, label)

    return "\n".join(
        (
            "# Generated by tools/scripts/base_head_match_matrix.py",
            "# Format: name|depth|cwd|command|arg...",
            f"head|{depth}|{config.head_repo}|{config.head_binary}",
            f"base|{depth}|{config.base_repo}|{config.base_binary}",
            "",
        )
    )


def build_depth_run(config: MatrixConfig, depth: int) -> DepthRun:
    run_dir = config.out_dir / f"depth-{depth}"
    engines_path = run_dir / "engines.generated.txt"
    match_path = run_dir / "match.jsonl"
    summary_path = run_dir / "summary.txt"
    command_path = run_dir / "command.txt"
    runner_command = [
        str(config.runner),
        "--black",
        "external:head",
        "--white",
        "external:base",
        "--games",
        str(config.games),
        "--swap-sides",
        "true",
        "--seed",
        str(config.seed),
        "--openings",
        str(config.openings),
        "--engines",
        str(engines_path),
        "--external-timeout-ms",
        str(config.external_timeout_ms),
        "--output",
        str(match_path),
        "--quiet",
    ]
    summary_command = [
        sys.executable,
        str(config.summary_script),
        "--input",
        str(match_path),
        "--by-opening",
    ]
    if config.allow_errors:
        summary_command.append("--allow-errors")

    return DepthRun(
        depth=depth,
        run_dir=run_dir,
        engines_path=engines_path,
        match_path=match_path,
        summary_path=summary_path,
        command_path=command_path,
        runner_command=runner_command,
        summary_command=summary_command,
    )


def write_depth_inputs(config: MatrixConfig, run: DepthRun) -> None:
    run.run_dir.mkdir(parents=True, exist_ok=True)
    run.engines_path.write_text(render_engine_config(config, run.depth), encoding="utf-8")
    command_text = "\n".join(
        (
            "# Runner command",
            quote_command(run.runner_command),
            "",
            "# Summary command",
            quote_command(run.summary_command),
            "",
        )
    )
    run.command_path.write_text(command_text, encoding="utf-8")


def summarize_match(match_path: Path, summary_path: Path) -> match_summary.Summary:
    records = match_summary.load_records(match_path)
    summary = match_summary.summarize(records)
    summary_text = match_summary.format_summary(match_path, summary, by_opening=True)
    summary_path.write_text(summary_text, encoding="utf-8")
    return summary


def detect_git_metadata(repo: Path) -> GitMetadata:
    def git_output(args: list[str]) -> str:
        completed = subprocess.run(
            ["git", "-C", str(repo), *args],
            check=False,
            stdout=subprocess.PIPE,
            stderr=subprocess.DEVNULL,
            text=True,
        )
        if completed.returncode != 0:
            return "unknown"
        text = completed.stdout.strip()
        return text if text else "unknown"

    return GitMetadata(
        ref=git_output(["rev-parse", "--abbrev-ref", "HEAD"]),
        sha=git_output(["rev-parse", "HEAD"]),
    )


def _md(value: object) -> str:
    return str(value).replace("|", "\\|")


def _fmt_float(value: float | None) -> str:
    if value is None:
        return "n/a"
    return f"{value:.2f}"


def render_summary_table(results: list[DepthResult]) -> str:
    lines = [
        "| depth | games | head wins | base wins | draws | head win rate | avg diff | avg plies | avg passes | errors | avg head time ms | avg base time ms | match JSONL | summary |",
        "| ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | :--- | :--- |",
    ]
    for result in results:
        summary = result.summary
        if summary is None:
            lines.append(
                f"| {result.run.depth} | 0 | 0 | 0 | 0 | n/a | n/a | n/a | n/a | n/a | n/a | n/a | {_md(result.run.match_path)} | {_md(result.run.summary_path)} |"
            )
            continue
        lines.append(
            "| "
            + " | ".join(
                (
                    str(result.run.depth),
                    str(summary.games),
                    str(summary.player_a_wins),
                    str(summary.player_b_wins),
                    str(summary.draws),
                    f"{summary.player_a_win_rate * 100.0:.2f}%",
                    f"{summary.average_diff:.2f}",
                    f"{summary.average_plies:.2f}",
                    f"{summary.average_passes:.2f}",
                    str(summary.error_games),
                    _fmt_float(summary.optional_average("time_ms_player_a")),
                    _fmt_float(summary.optional_average("time_ms_player_b")),
                    _md(result.run.match_path),
                    _md(result.run.summary_path),
                )
            )
            + " |"
        )
    return "\n".join(lines) + "\n"


def render_report(config: MatrixConfig, results: list[DepthResult]) -> str:
    base_git = detect_git_metadata(config.base_repo)
    head_git = detect_git_metadata(config.head_repo)
    timestamp = dt.datetime.now(dt.timezone.utc).isoformat(timespec="seconds")
    lines = [
        "# Base/Head Match Matrix",
        "",
        "Status: local deterministic match matrix.",
        "",
        "This is not an Elo estimate. Use it to catch obvious regressions or",
        "directional changes; stronger claims need larger game counts and broader",
        "opening coverage.",
        "",
        "## Run Metadata",
        "",
        f"- Generated at: {timestamp}",
        f"- Base repo: `{config.base_repo}`",
        f"- Base git ref: `{base_git.ref}`",
        f"- Base git SHA: `{base_git.sha}`",
        f"- Base binary: `{config.base_binary}`",
        f"- Head repo: `{config.head_repo}`",
        f"- Head git ref: `{head_git.ref}`",
        f"- Head git SHA: `{head_git.sha}`",
        f"- Head binary: `{config.head_binary}`",
        f"- Openings: `{config.openings}`",
        f"- Depths: `{','.join(str(depth) for depth in config.depths)}`",
        f"- Games per depth: `{config.games}`",
        f"- Seed: `{config.seed}`",
        f"- Swap sides: `true`",
        f"- External timeout ms: `{config.external_timeout_ms}`",
        "",
        "## Summary",
        "",
        render_summary_table(results).rstrip(),
        "",
        "## Commands",
        "",
    ]
    for result in results:
        lines.extend(
            (
                f"### Depth {result.run.depth}",
                "",
                "```sh",
                quote_command(result.run.runner_command),
                quote_command(result.run.summary_command),
                "```",
                "",
            )
        )

    lines.append("## Per-Depth Summaries")
    lines.append("")
    for result in results:
        lines.append(f"### Depth {result.run.depth}")
        lines.append("")
        if result.summary is None:
            lines.append(f"Run failed: {result.error or 'unknown error'}")
            lines.append("")
            continue
        try:
            summary_text = result.run.summary_path.read_text(encoding="utf-8").rstrip()
        except OSError:
            summary_text = "(summary text unavailable)"
        lines.append("```text")
        lines.append(summary_text)
        lines.append("```")
        lines.append("")

    return "\n".join(lines)


def run_matrix(config: MatrixConfig, *, dry_run: bool) -> int:
    results: list[DepthResult] = []
    config.out_dir.mkdir(parents=True, exist_ok=True)

    for depth in config.depths:
        run = build_depth_run(config, depth)
        write_depth_inputs(config, run)
        print(f"depth {depth}", flush=True)
        print(f"runner: {quote_command(run.runner_command)}", flush=True)
        print(f"summary: {quote_command(run.summary_command)}", flush=True)

        if dry_run:
            results.append(DepthResult(run=run, summary=None, runner_exit_code=0, error="dry run"))
            continue

        runner_exit_code = run_command(run.runner_command)
        if runner_exit_code != 0:
            results.append(
                DepthResult(
                    run=run,
                    summary=None,
                    runner_exit_code=runner_exit_code,
                    error=f"runner exited with {runner_exit_code}",
                )
            )
            continue

        try:
            summary = summarize_match(run.match_path, run.summary_path)
            results.append(DepthResult(run=run, summary=summary, runner_exit_code=0))
        except ScriptError as exc:
            results.append(DepthResult(run=run, summary=None, runner_exit_code=0, error=str(exc)))

    report_path = config.out_dir / "report.md"
    report_path.write_text(render_report(config, results), encoding="utf-8")
    print(f"report: {report_path}", flush=True)

    failed = [result for result in results if result.runner_exit_code != 0 or result.summary is None]
    errored = [
        result
        for result in results
        if result.summary is not None and result.summary.error_games > 0 and not config.allow_errors
    ]
    if failed or errored:
        return 1
    return 0


def _positive_int(value: str) -> int:
    try:
        parsed = int(value)
    except ValueError as exc:
        raise argparse.ArgumentTypeError(f"expected integer, got: {value}") from exc
    if parsed <= 0:
        raise argparse.ArgumentTypeError(f"expected positive integer, got: {value}")
    return parsed


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Run base/head external NBoard match matrices across search depths."
    )
    parser.add_argument("--base-build", required=True, help="base build directory")
    parser.add_argument("--head-build", required=True, help="head build directory")
    parser.add_argument("--base-repo", required=True, help="base repository/worktree directory")
    parser.add_argument("--head-repo", required=True, help="head repository/worktree directory")
    parser.add_argument("--openings", required=True, help="opening suite text file")
    parser.add_argument("--depths", required=True, help="comma-separated positive depths")
    parser.add_argument("--games", required=True, type=_positive_int, help="games per depth")
    parser.add_argument("--seed", required=True, type=int, help="base random seed")
    parser.add_argument("--out", required=True, help="output directory, normally under runs/")
    parser.add_argument("--runner", help="path to othello_match_runner; defaults to head build")
    parser.add_argument("--base-binary", help="path to base othello_nboard_engine")
    parser.add_argument("--head-binary", help="path to head othello_nboard_engine")
    parser.add_argument(
        "--summary-script",
        default=str(Path(__file__).with_name("match_summary.py")),
        help="path to match_summary.py for command recording",
    )
    parser.add_argument(
        "--external-timeout-ms",
        default=10000,
        type=_positive_int,
        help="timeout per external NBoard command sequence",
    )
    parser.add_argument(
        "--allow-errors",
        action="store_true",
        help="write a report and return success even if JSONL contains error games",
    )
    parser.add_argument("--dry-run", action="store_true", help="write commands/report without running matches")
    return parser.parse_args(argv)


def config_from_args(args: argparse.Namespace) -> MatrixConfig:
    base_build = Path(args.base_build)
    head_build = Path(args.head_build)
    return MatrixConfig(
        base_build=base_build,
        head_build=head_build,
        base_repo=Path(args.base_repo),
        head_repo=Path(args.head_repo),
        openings=Path(args.openings),
        depths=parse_depth_list(args.depths),
        games=args.games,
        seed=args.seed,
        out_dir=Path(args.out),
        runner=Path(args.runner) if args.runner else head_build / "othello_match_runner",
        base_binary=Path(args.base_binary) if args.base_binary else base_build / "othello_nboard_engine",
        head_binary=Path(args.head_binary) if args.head_binary else head_build / "othello_nboard_engine",
        summary_script=Path(args.summary_script),
        external_timeout_ms=args.external_timeout_ms,
        allow_errors=args.allow_errors,
    )


def main(argv: list[str] | None = None) -> int:
    try:
        args = parse_args(argv)
        config = config_from_args(args)
        return run_matrix(config, dry_run=args.dry_run)
    except ScriptError as exc:
        print(exc, file=sys.stderr)
        return exc.exit_code


if __name__ == "__main__":
    raise SystemExit(main())
