#include "test_helpers.hpp"

#include <array>
#include <catch2/catch_test_macros.hpp>
#include <othello/othello.hpp>
#include <string>
#include <string_view>

using othello::Board;

TEST_CASE("Initial board text parses to the initial board", "[notation]") {
    const auto board = othello::board_from_string(othello::test::initial_board_text);

    REQUIRE(board.has_value());
    CHECK(othello::test::same_board(*board, Board::initial()));
}

TEST_CASE("Initial board formats to text", "[notation]") {
    CHECK(othello::to_string(Board::initial()) == std::string{othello::test::initial_board_text});
}

TEST_CASE("Board formatting and parsing round-trips a non-initial board", "[notation]") {
    const auto board = othello::apply_move(Board::initial(), othello::test::square("d3"));

    REQUIRE(board.has_value());

    const std::string text = othello::to_string(*board);
    const auto parsed = othello::board_from_string(text);

    REQUIRE(parsed.has_value());
    CHECK(othello::test::same_board(*parsed, *board));
}

TEST_CASE("Malformed board strings are rejected", "[notation]") {
    constexpr std::array malformed{
        R"(........
........
........
...BW...
...WB...
........
........
side=B)",
        R"(........
........
........
...BW...
...WB...
........
........
........
........
side=B)",
        R"(.......
........
........
...BW...
...WB...
........
........
........
side=B)",
        R"(........
........
........
...BX...
...WB...
........
........
........
side=B)",
        R"(........
........
........
...BW...
...WB...
........
........
........
side=Black)",
        R"(........
........
........
...BW...
...WB...
........
........
........)",
    };

    for (const std::string_view text : malformed) {
        CAPTURE(std::string{text});
        CHECK_FALSE(othello::board_from_string(text).has_value());
    }
}
