if(NOT DEFINED EXPECT_FAILURE_COMMAND)
    message(FATAL_ERROR "EXPECT_FAILURE_COMMAND is required")
endif()

if(NOT DEFINED EXPECT_FAILURE_PATTERN)
    message(FATAL_ERROR "EXPECT_FAILURE_PATTERN is required")
endif()

set(EXPECT_FAILURE_COMMAND_ARGS)
if(DEFINED EXPECT_FAILURE_ARGS AND NOT EXPECT_FAILURE_ARGS STREQUAL "")
    string(REPLACE "|" ";" EXPECT_FAILURE_COMMAND_ARGS "${EXPECT_FAILURE_ARGS}")
endif()

execute_process(
    COMMAND "${EXPECT_FAILURE_COMMAND}" ${EXPECT_FAILURE_COMMAND_ARGS}
    RESULT_VARIABLE EXPECT_FAILURE_RESULT
    OUTPUT_VARIABLE EXPECT_FAILURE_STDOUT
    ERROR_VARIABLE EXPECT_FAILURE_STDERR
)

set(EXPECT_FAILURE_OUTPUT "${EXPECT_FAILURE_STDOUT}${EXPECT_FAILURE_STDERR}")

if(EXPECT_FAILURE_RESULT EQUAL 0)
    message(FATAL_ERROR "expected command to fail, but it exited 0\n${EXPECT_FAILURE_OUTPUT}")
endif()

if(NOT EXPECT_FAILURE_OUTPUT MATCHES "${EXPECT_FAILURE_PATTERN}")
    message(
        FATAL_ERROR
        "expected output to match '${EXPECT_FAILURE_PATTERN}'\n${EXPECT_FAILURE_OUTPUT}"
    )
endif()
